android_config: &android_config
  docker:
    - image: circleci/android:api-28-alpha
  environment:
    # kotlin.incremental=false and kotlin.compiler.execution.strategy=in-process are required due to an issue with the Kotlin compiler in
    # memory constrained environments: https://youtrack.jetbrains.com/issue/KT-15562
    GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    GRADLEW: "./gradlew --stacktrace"

copy_gradle_properties: &copy_gradle_properties
  run:
    name: Setup gradle.properties
    command: cp gradle.properties gradle.properties && cp libs/login/gradle.properties libs/login/gradle.properties

orbs:
  android: wordpress-mobile/android@0.0.19
  bundle-install: toshimaru/bundle-install@0.1.1

version: 2.1
jobs:
  test:
    <<: *android_config
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: test-cache
      - <<: *copy_gradle_properties
      - run:
          name: Test
          command: $GRADLEW testVanillaRelease
      - android/save-gradle-cache:
          cache-prefix: test-cache
      - android/save-test-results
  lint:
    <<: *android_config
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: lint-cache
      - <<: *copy_gradle_properties
      - run:
          name: Checkstyle
          command: $GRADLEW checkstyle
      - run:
          name: ktlint
          command: $GRADLEW ciktlint
      - run:
          name: Lint
          command: $GRADLEW lintVanillaRelease || (grep -A20 -B2 'severity="Error"' -r --include="*.xml" WordPress libs; exit 1)
      - run:
          name: Violations
          when: on_fail
          command: |
            if [ -n "$GITHUB_API_TOKEN" ]; then
              $GRADLEW violationCommentsToGitHub -DGITHUB_PULLREQUESTID=${CIRCLE_PULL_REQUEST##*/} -DGITHUB_OAUTH2TOKEN=$GITHUB_API_TOKEN
            else
              echo "Not posting lint errors to Github because \$GITHUB_API_TOKEN is not found"
            fi 
      - android/save-gradle-cache:
          cache-prefix: lint-cache
      - store_artifacts:
          path: WordPress/build/reports
          destination: reports
  strings-check:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
          name: Validate login strings
          command: bundle exec fastlane validate_login_strings pr_url:$CIRCLE_PULL_REQUEST

workflows:
  wordpress_android:
    jobs:
      - strings-check
      - test
      - lint
